apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    app: prometheus
    tier: monitoring
    service: prometheus
spec:
  selector:
    app: prometheus
  type: ClusterIP  # Change to NodePort if needed for browser access
  ports:
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: http
