apiVersion: v1
kind: Service
metadata:
  name: redis-cart
  labels:
    app: redis-cart
    tier: backend
    service: redis
spec:
  type: ClusterIP
  selector:
    app: redis-cart
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
    appProtocol: redis
